apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fastapiapp.fullname" . }}
  labels:
    {{- include "fastapiapp.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "fastapiapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fastapiapp.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fastapiapp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          {{- with .Values.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP

          {{- if .Values.probes.http.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.http.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.http.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.http.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.http.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.http.failureThreshold }}
            successThreshold: {{ .Values.probes.http.successThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.http.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.http.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.http.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.http.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.http.failureThreshold }}
            successThreshold: {{ .Values.probes.http.successThreshold }}
          {{- else if .Values.probes.tcp.enabled }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.probes.tcp.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.tcp.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.tcp.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.tcp.failureThreshold }}
            successThreshold: {{ .Values.probes.tcp.successThreshold }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.probes.tcp.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.tcp.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.tcp.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.tcp.failureThreshold }}
            successThreshold: {{ .Values.probes.tcp.successThreshold }}
          {{- end }}

          {{- if .Values.extraEnv }}
          env:
            {{- toYaml .Values.extraEnv | nindent 12 }}
          {{- end }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
